#Jekyll configuration
name: 'Matt Craddock'
description: I am a cognitive neuroscientist and here I blog about stats and EEG
gems: 
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
highlighter: rouge


permalink: /blog/:year/:month/:day/:title
url: "https://craddm.github.io"
baseurl: "/"
baseurlknitr: "/"
twitter: Matt_Craddock

paginate: 5
homepostlimit:  4

title: "Time-frequency transform"
description: "Matt Craddock's blog about cognitive neuroscience and other animals"

comments: true
disqus: true

github:
  repo:           https://github.com/craddm/craddm.github.io

#google tracking
google_analytics: UA-84391127-1
