#Jekyll configuration
name: Matt Craddock
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
permalink: /blog/:year/:month/:day/:title
url: "http://craddm.github.io"