#Jekyll configuration
name: 'Matt Craddock'
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
permalink: /blog/:year/:month/:day/:title
url: "https://craddm.github.io"
highlighter: rouge
baseurl: "/"
baseurlknitr: "/"
gems: [jekyll-paginate]
paginate: 5
homepostlimit:  4
title: "Time-frequency transform"
description: "Matt Craddock's blog about cognitive neuroscience and other animals"
comments: true
disqus: true