#Jekyll configuration
name: 'Matt Craddock'
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
permalink: /blog/:year/:month/:day/:title
url: "https://craddm.github.io"
highlighter: rouge
baseurl: "/"
baseurlknitr: "/"
paginate: 5
homepostlimit:  4
title: "Matt Craddock"
description: "Cognitive neuroscience and other animals"