---
title: "Python in R"
author: "Matt Craddock"
date: "22 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadPackages}
library(tidyverse)
library(ggplot2)
library(scales)
library(multitaper)
library(bspec)
```

```{python, engine.path = "C:\\Users\\Matt\\Anaconda3\\envs\\NewPython\\python.exe"}
import mne
import numpy as np
import pandas
import feather

eogChans = (64,65,66,67)
miscChans = (68,69,70,71)
raw = mne.io.read_raw_edf('D:\Dropbox\EEGData\Leeds\InteroExtero\S99\Extero\S99ExteroSSDTB2.bdf',preload = True,eog = eogChans,misc = miscChans)
raw.info['bads'] = ['EXG7','EXG8']
picks = mne.pick_types(raw.info, meg=False, eeg=True, eog=False, exclude='bads')
events = mne.find_events(raw, stim_channel='STI 014')
montage = mne.channels.read_montage('standard_1020')
raw.set_montage(montage)
raw_avg_ref, _ = mne.io.set_eeg_reference(raw,None)
#raw_avg_ref.filter(1, 40, n_jobs=2)
raw_avg_ref.filter(1, 60)
event_id = dict(light=100, noLight=128)  # event trigger and conditions
tmin = -0.2  # start of each epoch (200ms before the trigger)
tmax = 0.6  # end of each epoch (500ms after the trigger)
baseline = (None, 0)
epochs = mne.Epochs(raw, events=events, event_id=event_id, tmin=tmin,
                    tmax=tmax, picks=picks, add_eeg_ref=False,preload = True)
epochs_avg = epochs.average()
df = epochs_avg.to_data_frame()
df.to_csv('C:\\Users\\Matt\\Documents\\temp\\my_evoked.csv')
dfRaw = epochs.to_data_frame()
dfRaw.to_csv('C:\\Users\\Matt\\Documents\\temp\\my_epochs.csv')

```

```{r}
newdat <- read_csv('C:\\Users\\Matt\\Documents\\temp\\my_evoked.csv')
EEGdat <- gather(newdat,electrode,amplitude,-time)

theme_set(theme_bw())

levCat.plot <- ggplot(EEGdat,aes(time,amplitude))+
  geom_line(aes(colour = electrode))

levCat.plot

levCat.plot <- ggplot(EEGdat,aes(time,amplitude))+
  stat_summary(fun.y= mean,geom = "line")
```

```{r}
electrodeLocs <- read_delim("https://raw.githubusercontent.com/craddm/ExploringERPs/master/biosemi70elecs.loc", "\t", escape_double = FALSE, col_names = c("chanNo","theta","radius","electrode"), trim_ws = TRUE)
electrodeLocs$radianTheta <- pi/180*electrodeLocs$theta
electrodeLocs <- electrodeLocs %>%
  mutate(x = .$radius*sin(.$radianTheta),
         y = .$radius*cos(.$radianTheta))

theme_topo <- function(base_size = 12)
  {
  theme_bw(base_size = base_size) %+replace%
      theme(
            rect             = element_blank(),
            line             = element_blank(),
            axis.text = element_blank(),
            axis.title = element_blank()
           )
}

circleFun <- function(center = c(0,0),diameter = 1, npoints = 100) {
  r = diameter / 2
  tt <- seq(0,2*pi,length.out = npoints)
  xx <- center[1] + r * cos(tt)
  yy <- center[2] + r * sin(tt)
  return(data.frame(x = xx, y = yy))
}

headShape <- circleFun(c(0, 0), round(max(electrodeLocs$x)), npoints = 100) # 0
nose <- data.frame(x = c(-0.05,0,.05),y=c(.495,.55,.495))
allData <- EEGdat %>% left_join(electrodeLocs, by = "electrode")
allData
```
```{r}
jet.colors <-
  colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan",
                     "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))
singleTimepoint <- filter(allData,time == 170)
rmax <- .75   #specify a maximum boundary for the grid
gridRes <- 67 #specify the interpolation grid resolution

## Create a function to perform Matlab's v4 interpolation.
## Takes as input a data-frame with columns x, y, and z (x co-ordinates, y co-ordinates, and amplitude)
## and variables xo and yo, the co-ordinates which will be use to create a grid for interpolation

v4Interp <- function(df,xo,yo) {
  xo <- matrix(rep(xo,length(yo)),nrow = length(xo),ncol = length(yo))
  yo <- t(matrix(rep(yo,length(xo)),nrow = length(yo),ncol = length(xo)))
  xy <- df$x + df$y*sqrt(as.complex(-1))
  d <- matrix(rep(xy,length(xy)),nrow = length(xy), ncol = length(xy))
  d <- abs(d - t(d))
  diag(d) <- 1
  g <- (d^2) * (log(d)-1)   # Green's function.
  diag(g) <- 0
  weights <- qr.solve(g,df$z)
  xy <- t(xy)
  outmat <- matrix(nrow = gridRes,ncol = gridRes)
  for (i in 1:gridRes){
    for (j in 1:gridRes) {
      test4 <- abs((xo[i,j] + sqrt(as.complex(-1))*yo[i,j]) - xy)
      g <- (test4^2) * (log(test4)-1)
      outmat[i,j] <- g %*% weights
      }
    }
  return(list(x = xo[,1],y = yo[1,],z = outmat))
}

## Create data frame to be used for interpolation
testDat<- data.frame(x = singleTimepoint$x,
                     y = singleTimepoint$y,
                     z = singleTimepoint$amplitude)

#Create the interpolation grid
xo <- seq(min(-rmax, testDat$x), max(rmax, testDat$x), length = gridRes)
yo <- seq(max(rmax, testDat$y), min(-rmax, testDat$y), length = gridRes)

finalOut <- v4Interp(testDat, xo, yo)

interpV4 <- data.frame(x = finalOut$x,
                       finalOut$z)
names(interpV4)[1:length(finalOut$y)+1] <- finalOut$y

interpV4 <- gather(interpV4,
                   key = y,
                   value = amplitude,
                   -x,
                   convert = TRUE) 

interpV4$incircle <- (interpV4$x)^2 + (interpV4$y)^2 < 0.7 ^ 2 # mark
maskRing <- circleFun(diameter = 1.42) 
v4plot <- ggplot(interpV4[interpV4$incircle,],aes(x = x, y = y, fill = amplitude))+
  geom_raster()+
  stat_contour(aes(z = amplitude), colour = "black",binwidth = 0.6)+
  theme_topo()+
   geom_path(data = maskRing,
            aes(x, y, z = NULL, fill =NULL),
            colour = "white",
            size = 6)+
  scale_fill_gradientn(colours = jet.colors(10),
                       limits = c(-5,5),
                       guide = "colourbar",
                       oob = squish)+
  geom_point(data = singleTimepoint,
             aes(x,y),
             size = 1)+
  geom_path(data = headShape,
            aes(x,y,z = NULL,fill = NULL),
            size = 1.5)+
  geom_path(data = nose,
            aes(x, y, z = NULL, fill = NULL),
            size = 1.5)+
  coord_equal()
v4plot
```
```{r}
yy<- EEGdat %>% filter(electrode == "Cz")

yfft <- fft(yy$amplitude)
length(yfft)
plot(log10(abs(yfft[1:50])))
yspec<-spectrum(yy$amplitude,demean = TRUE,log = "dB",fast = TRUE,taper = 0.1)
yts <- ts(yy$amplitude,start = c(-.2,1),frequency = 1024)
plot(yspec$freq[1:150],log(yspec$spec[1:150]))

zz<- spec.mtm(yts)
plot(zz$freq[1:80],log(zz$spec[1:80]),type = "l")

spectrum(yts,log = "dB")

gg <- welchPSD(yts,seglength = 0.8)
ff <- empiricalSpectrum(yts)
plot(gg$frequency[1:50],log10(gg$power[1:50]),type = "l")
plot(ff$frequency[1:50],log10(ff$power[1:50]),type = "l")
```

