---
title: "testing ICA"
author: "Matt Craddock"
date: "23 April 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
library(tidyverse)
library(JADE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, warnings = FALSE}
clean_data <- read_csv('C:\\Users\\Matt\\Documents\\Github\\ExploringERPs\\epochs_clean.csv')
clean_data
```

```{r}
n_epochs <- length(unique(clean_data$epoch))

# zero-mean columns
xx <- scale(data.matrix(clean_data[,4:67]),scale = FALSE)
ss <- svd(xx)
SSSS <- MASS::ginv(diag(ss$d)) %*% t(ss$v)
ttt <- SSSS %*% t(xx)

X <- ttt
dim(X) <- c(64,230,466)


k <-1
m <- 64
pm <- m*77 # for convenience
N <- 230
M <- matrix(NA,nrow = 64, ncol = pm)
for (u in seq(1, pm, m)) {
  k <- k+1
  for (tlag in 1:n_epochs) {
     if (tlag == 1) {
         Rxp=X[,k:N,tlag] %*% t(X[,1:(N-k+1),tlag]) /(N-k+1)/n_epochs }
     else {
         Rxp=Rxp+X[,k:N,tlag] %*% t(X[,1:(N-k+1),tlag])/(N-k+1)/n_epochs
     }
   M[,u:(u+m-1)] <- norm(Rxp,'F') * Rxp #  % Frobenius norm =
 }
}

M2 <- M
dim(M2) <- c(64,64, 4928/64)

M3 <- rjd(M2, maxiter = 300)

final_zz <- data.frame(M3$V)

names(final_zz) <- 1:64
final_zz$electrode <- names(clean_data[,4:67])



```


```{r}
#
# Perform joint diagonalization
#
epsil <- 1/sqrt(N)/100 
encore <- 1
V <- diag(1, nrow = m)
step_n <- 0
while encore 
 encore=0
 for (p in 1:(m-1)){
  for q=p+1:m
   % Perform Givens rotation
   g=[   M[p, seq(p, pm, m)]-M[q, seq(q, pm, m)],
         M[p, seq(q, pm, m)]+M[q, seq(p, pm, m)],  
      i*(M[q, seq(p, pm, m)]-M[p, seq(q, pm, m)])]
	  
[vcp,D] = eig(real(g*t(g))); 
          [la,K]=sort(diag(D));
   angles=vcp(:,K(3));
   angles=sign(angles(1))*angles;
   c=sqrt(0.5+angles(1)/2);
   sr=0.5*(angles(2)-j*angles(3))/c; 
   sc=conj(sr);
   oui = abs(sr)>epsil ;
   encore=encore | oui ;
   if oui , % Update the M and V matrices 
    colp=M(:,p:m:pm);
    colq=M(:,q:m:pm);
    M(:,p:m:pm)=c*colp+sr*colq;
    M(:,q:m:pm)=c*colq-sc*colp;
    rowp=M(p,:);
    rowq=M(q,:);
    M(p,:)=c*rowp+sc*rowq;
    M(q,:)=c*rowq-sr*rowp;
    temp=V(:,p);
    V(:,p)=c*V(:,p)+sr*V(:,q);
    V(:,q)=c*V(:,q)-sc*temp;
   end%% if
  end%% q loop
 }
 step_n=step_n+1;
fprintf('%d step\n',step_n);
end%% while

```

