---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(copula)
library(psych)
library(afex)
```
```{r generateMVnorm}
nSubs <- 24
nTrials <- 50

myCop<- normalCopula(param=0.6, dim = 3, dispstr = "ex")
myMvd <- mvdc(copula=myCop, margins=c("lnorm", "lnorm","lnorm"),
              paramMargins=list(list(meanlog=0.3, sdlog=0.9),
                                list(meanlog=0.3, sdlog=0.9),
                                list(meanlog=(0.3+rnorm(1,mean = 0,sd = 0.05)),sdlog=1)
                                ))

MVNdata <- replicate(nSubs,rMvdc(nTrials,myMvd),simplify = FALSE)
MVNdata <- bind_rows(lapply(MVNdata, data.frame, stringsAsFactors = FALSE)) %>%
  mutate(Subject = rep(1:nSubs,each = nTrials)) 
  names(MVNdata) <- c("condA","condB","baseline","Subject")

pairs.panels(MVNdata[1:3],method = "spearman")

```
```{r}
MVNdata %>% gather(condition,power,-Subject) %>%
ggplot(aes(x = power,fill = condition))+geom_density(alpha =.3)+facet_wrap(~Subject)
```

```{r}

nSubs <- 24
nTrials <- 80

myCop<- normalCopula(param=0.5, dim = 3)
tmpFunc <- function(x) {
  MVNdata <- replicate(nSubs,{
    myMvd <- mvdc(copula=myCop, margins=c("lnorm", "lnorm","lnorm"),
                  paramMargins=list(list(meanlog=(0.3+rnorm(1,mean = 0,sd = 0.03)), sdlog=1),
                                    list(meanlog=(0.3+rnorm(1,mean = 0,sd = 0.03)), sdlog=1),
                                    list(meanlog=(0.3+rnorm(1,mean = 0,sd = 0.03)),sdlog=1)))
    rMvdc(nTrials, myMvd)}, simplify = FALSE)
  
  MVNdata <-bind_rows(lapply(MVNdata, data.frame, stringsAsFactors = FALSE)) %>%
    mutate(Subject = rep(1:nSubs, each = nTrials))
  names(MVNdata) <- c("condA", "condB", "baseline", "Subject")
  
  meanSummary <- MVNdata %>%
    gather(condition, power, -Subject) %>%
    group_by(Subject, condition) %>%
    summarise(
      meanPow = mean(power),
      medPow = median(power),
      sdPow = sd(power)
      ) %>% 
    ungroup()
  
  stdSummary <- MVNdata %>%
    gather(condition, power, -Subject) %>%
    group_by(Subject, condition) %>%
    summarise(sdPow = sd(power)) %>%  
    ungroup()
  
  baseline <- meanSummary %>%
    filter(condition == "baseline") %>%
    select(c(1, 3, 4, 5)) %>%
    gather(measure, baseline, -Subject) %>%
    arrange(Subject)
  
  meanBaseline <- meanSummary %>%
    filter(condition != "baseline") %>%
    gather(measure, power, -Subject, -condition) %>%
    spread(measure, power) %>%
    inner_join(filter(baseline, measure == "meanPow"),by = "Subject", .) %>%
    mutate(
      subBLmean = meanPow - baseline,
      divBLmean = meanPow / baseline,
      zBLmean = (meanPow - baseline) / sdPow
      )
  
    medBaseline <- meanSummary %>%
    filter(condition != "baseline") %>%
    gather(measure, power, -Subject, -condition) %>%
    spread(measure, power) %>%
    inner_join(filter(baseline, measure == "medPow"),by = "Subject", .) %>%
    mutate(
      subBLmean = meanPow - baseline,
      divBLmean = meanPow / baseline,
      zBLmean = (meanPow - baseline) / sdPow
      )
  
  noBl <- t.test(meanPow~condition,paired = TRUE,data = meanBaseline)
  subBl <- t.test(subBLmean~condition,paired = TRUE,data = meanBaseline)
  divBl <- t.test(divBLmean~condition,paired = TRUE,data = meanBaseline)
  zBl <- t.test(zBLmean~condition,paired = TRUE,data = meanBaseline)
  
  subBlMed <- t.test(subBLmean~condition,paired = TRUE,data = medBaseline)
  divBlMed <- t.test(divBLmean~condition,paired = TRUE,data = medBaseline)
  zBlMed <- t.test(zBLmean~condition,paired = TRUE,data = medBaseline)
  
  return(list("noBl" = noBl$p.value,"subP" = subBl$p.value,"divP" = divBl$p.value,"ZP" = zBl$p.value,"subMedP" = subBlMed$p.value,"divMedP" = divBlMed$p.value,"zBlMed" = zBlMed$p.value))
  }
out <- replicate(1000,tmpFunc(1))
```

```{r}
mean(out[1,] < .05)
mean(out[2,] < .05)
mean(out[3,] < .05)
mean(out[4,] < .05)
mean(out[5,] < .05)
mean(out[6,] < .05)
mean(out[7,] < .05)
```

```{r}
ggplot(meanBaseline,aes(subBLmean,fill = condition))+geom_density(alpha =0.3)
ggplot(meanBaseline,aes(divBLmean,fill = condition))+geom_density(alpha =0.3)
ggplot(meanBaseline,aes(zBLmean,fill = condition))+geom_density(alpha =0.3)

```

```{r generateMore}
nSubs <- 24
nTrials <- 100

myCop<- normalCopula(param=0.3, dim = 6, dispstr = "ex")
myMvd <- mvdc(copula=myCop, margins=c("lnorm", "lnorm","lnorm","lnorm","lnorm","lnorm"),
              paramMargins=list(list(meanlog=0.21, sdlog=1),
                                list(meanlog=0.27, sdlog=1),
                                list(meanlog=0.25,sdlog=1),
                                list(meanlog=(0.21*.5),sdlog=(1*.5)),
                                list(meanlog=(0.27*.5),sdlog=(1*.5)),
                                list(meanlog=(0.25*1),sdlog=(1*1))
                                ))

MVNdata <- replicate(nSubs,rMvdc(nTrials,myMvd),simplify = FALSE)
MVNdata <- bind_rows(lapply(MVNdata, data.frame, stringsAsFactors = FALSE)) %>%
  mutate(Subject = rep(1:nSubs,each = nTrials)) 
  names(MVNdata) <- c("condA.L","condB.L","baseline.L","condA.R","condB.R","baseline.R","Subject")

pairs.panels(MVNdata[1:6],method = "spearman")

```

```{r}
meanSummary<- MVNdata %>%
    gather(condition, power, -Subject) %>%
    group_by(Subject, condition) %>%
    summarise(
      meanPow = mean(power),
      medPow = median(power),
      sdPow = sd(power)
      ) %>% 
    ungroup()

baselineData <- meanSummary %>%
  filter(condition == "baseline.L" |condition == "baseline.R") %>%
  separate(condition,c("BL","hemisphere")) %>%
  select(c(1,3,4)) %>%
  rename(baseline = meanPow)  

funcData <- meanSummary %>%
  filter(condition != "baseline.L" & condition != "baseline.R") %>%
  separate(condition,c("condition","hemisphere")) %>%
  inner_join(baselineData,.,by=c("Subject","hemisphere")) %>%
  select(c(1,2,3,4,5)) %>%
  mutate(subBL = meanPow - baseline,
         divBL = meanPow / baseline)
```

```{r}
absPow <- aov_ez("Subject","meanPow",data = funcData,within = c("condition","hemisphere"))
subPow <- aov_ez("Subject","subBL",data = funcData,within = c("condition","hemisphere"))
divPow <- aov_ez("Subject","divBL",data = funcData,within = c("condition","hemisphere"))

absPow
subPow
divPow
```


```{r}
library(lsmeans)
lsmip(absPow, hemisphere ~ condition)
lsmip(subPow, hemisphere ~ condition)
lsmip(divPow, hemisphere ~ condition)
```